a=int(input("enter the 1st number:"))
b=int(input("enter the 2nd number:"))
print("sum",a+b)
print("sub",a-b)
print("mul",a*b)
print("div",a/b)
print("mod",a%b)
print("fl_div",a//b)
print("exp",a**b)