a=int(input("enter the 1st number : "))
b=int(input("enter the 2nd number : "))
c=input("enter a string : ")
d=input("enter another string :")
print(a==b)
print(a!=b)
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)
print(c==d)
print(c!=d)
print(c>d)
